theme: jekyll-theme-cayman

title: 浮生记
description: 世事茫茫，光阴有限，算来何必奔忙？人生碌碌，竞短论长，却不道荣枯有数，得失难量。

blog: "https://fushengji.github.io/blog/"
library: "https://fushengji.github.io/library/"

footer: Recording the floating life.
